[workspace]
authors = ["ZHU Yuhao 朱宇浩 <dr.yuhao.zhu@outlook.com>"]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "my-first-mojo-project"
platforms = ["osx-arm64"]
version = "20250904"

[tasks]
test = "bash test.sh"
verify = "zsh verify.sh"

[dependencies]
coreutils = ">=9.0"
decimo = "==0.10.0"
ipykernel = ">7.0"
mojo = "==1.0.0b1"
numpy = ">=2.4.2,<3"
python = ">=3.13,<3.14"
